# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/overlay_default.ipynb.

# %% auto 0
__all__ = ['background_color', 'table_row', 'table_headers', 'table', 'timeout_wrapper']

# %% ../../nbs/overlay_default.ipynb 1
import dash_bootstrap_components as dbc
from dash import html

# %% ../../nbs/overlay_default.ipynb 2
background_color = "rgba(64,64,64,0.95)"


def table_row(*args):
    cells = [
        html.Td(arg, className=f"align-text-top text-{'end' if i else 'start'} bg-transparent")
        for i, arg in enumerate(args)
    ]
    return html.Tr(cells)


def table_headers(*args):
    cells = [
        html.Th(h, className=f"text-{'end' if i else 'start'} bg-transparent")
        for i, h in enumerate(args)
    ]
    return html.Thead(html.Tr(cells))


def table(headers, rows):
    header = table_headers(*headers)
    body = html.Tbody([table_row(*row) for row in rows])
    return dbc.Table([header, body], class_name="p-1")


def timeout_wrapper(children, timeout, class_name=""):
    return dbc.Alert(
        children=children,
        class_name=f"p-0 m-0 {class_name}",
        color="rgba(0,0,0,0)",
        is_open=True,
        duration=timeout,
    )
